# Server
server.port=5000

# App name
spring.application.name=ccms-backend

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/ccms_db
spring.mongodb.database=ccms_db

# JWT
app.jwt.secret=ccms_super_secret_jwt_key_2025_spring_boot_mongodb
app.jwt.expiration=604800000

# CORS
app.cors.allowed-origins=http://localhost:5173

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.ccms=DEBUG